roles:
  spine1:
    fabric: network1
    hostname: spine1.net.testco.org
    protocols:
      dns:
        nameservers:
            - 10.5.5.115
      ntp:
        client:
          timezone: America/Chicago
          servers:
              - pool.ntp.org
              - 0.cumulusnetworks.pool.ntp.org
              - 1.cumulusnetworks.pool.ntp.org
              - 2.cumulusnetworks.pool.ntp.org
  spine2:
    fabric: network1
    hostname: spine2.net.testco.org
    protocols:
      dns:
        nameservers:
            - 10.5.5.115
    ntp:
        client:
          timezone: America/Chicago
          servers:
              - pool.ntp.org
              - 0.cumulusnetworks.pool.ntp.org
              - 1.cumulusnetworks.pool.ntp.org
              - 2.cumulusnetworks.pool.ntp.org


fabrics:
  network1:
    credentials:
      username: cumulus
      password: CumulusLinux!

appliances:
  0c-b3-6d-f1-11-00:
    hostname: 10.5.5.33
    role: spine1
    plugin_package: cumulus
  0c-b3-6d-9c-67-00:
    hostname: 10.5.5.34
    role: spine2
    plugin_package: cumulus
