roles:
  spine1:
    fabric: network1
    interfaces:
      1G:
        1-5:
          tagged_vlans: [2-5]
          untagged_vlan: 1
        6:
          untagged_vlan: 5
    protocols:
      dns:
        nameservers:
              - 10.5.5.115
              - 8.8.8.8
              - 8.8.4.4
      ntp:
        client:
          timezone: America/Chicago
          servers:
              - pool.ntp.org
              - 0.cumulusnetworks.pool.ntp.orgdns:
        nameservers:
            - 10.5.5.115
            - 8.8.8.8
            - 8.8.4.4
      ntp:
        client:
          timezone: America/Chicago
          servers:
              - pool.ntp.org
              - 0.cumulusnetworks.pool.ntp.org
  spine2:
    interfaces:
      1G:
        1-3:
          tagged_vlans: [2, 3, 4, 5]

    fabric: network1
    hostname: spine2.net.testco.org
    protocols:
      dns:
        nameservers:
            - 10.5.5.115
            - 8.8.8.8
            - 8.8.4.4
      ntp:
        client:
          timezone: America/Chicago
          servers:
              - pool.ntp.org
              - 0.cumulusnetworks.pool.ntp.org



fabrics:
  network1:
    credentials:
      username: cumulus
      password: CumulusLinux!
    vlans:
      1-5:
      6:
        description: Data
      30:
        description: Public
      11-29:

appliances:
  sw1:
    hostname: 10.5.5.33
    role: spine1
    plugin_package: cumulus
  sw2:
    hostname: 10.5.5.34
    role: spine2
    plugin_package: cumulus
  sw3:
    hostname: 10.5.5.44
    role: spine2
    plugin_package: cumulus
  sw4:
    hostname: 10.5.5.45
    role: spine2
    plugin_package: cumulus
