roles:
  spine1:
    fabric: network1
    hostname: spine1.net.testco.org
  spine2:
    fabric: network1
    hostname: spine2.net.testco.org
    protocols:
      dns:
        nameservers:
            - 10.5.5.115


fabrics:
  network1:
    credentials:
      username: cumulus
      password: CumulusLinux!

appliances:
  0c-b3-6d-f1-11-00:
    hostname: 10.5.5.33
    role: spine1
    plugin_package: cumulus
  0c-b3-6d-9c-67-00:
    hostname: 10.5.5.34
    role: spine2
    plugin_package: cumulus
